### ISSUE TITLE
Help enabling wmma instructions

### ISSUE THREAD

**Issue by spayne** [ROCm/Tensile#1943]
I used the the example at the bottom of https://github.com/ROCm/Tensile/wiki#quick-example-ubuntu to generate a set of solutions.

However, I noticed that none of the generated solutions are using the WMMA instructions.  My architecture does have HasWMMA=1.  

I confirmed that kernel["EnableMatrixInstructions'] is False in the kernel writer code... so that's not good - the problem is probably up the stack from there.

I thought I could add EnableMatrixInstructions to the rocblas_sgemm_example.yaml but I get an error Tensile::FATAL: Invalid parameter name: EnableMatrixInstruction

So:
* is it possible to enable and disable matrix instructions through the yaml?  If so how?
* if not, is there another way to force this setting on or off?

Thanks!

**Comment by ppanchad-amd** [comment]
Hi @spayne, internal ticket has been created to assist with your questions. Thanks!

**Comment by schung-amd** [comment]
Hi @spayne, I can't repro with the specific example because something else is broken on my end, but what happens when you generate solutions using one of the WMMA tests (e.g. Tensile/Tests/pre_checkin/wmma/hgemm_wmma.yaml)? This seems to be generating matrix instructions for me. Is this how you're verifying the presence of WMMA instructions, or is there something else you're checking?

**Comment by schung-amd** [comment]
Following up on this, it looks like the relevant parameter to add to the yaml is MatrixInstruction, and the documentation is [here](https://github.com/ROCm/Tensile/blob/fceee9948c7ce5e286a2960e97fef9a9f738fc5b/Tensile/Common.py#L1014). Let me know if the WMMA test, which sets this parameter, works for you; otherwise there might be an issue in your configuration.

**Comment by jfactory07** [comment]
@schung-amd  I think we need add an option like [MFMA ](https://github.com/ROCm/Tensile/blob/develop/tuning/automation/GenerateTuningConfigurations.py#L797 ) for WMMA in  GenerateTuningConfigurations.py

**Comment by schung-amd** [comment]
@jfactory07 From what I can tell WMMA is lumped in with MFMA, as both are matrix core instructions, and as long as Tensile is informed that you want matrix instructions (i.e. through the `mfma` argument in the .py you linked) it should use WMMA if supported. The documentation isn't very clear, though, and maybe this argument should be named something else; I'll reach out to the internal team about this.

**Comment by schung-amd** [comment]
A nuance for WMMA specifically: these instructions are only supported for matrix size 16x16x16, and any value of the `MatrixInstruction` parameter other than [16,16,16,1] will only result in MFMA instructions and no WMMA instructions.

**Comment by schung-amd** [comment]
Closing this, if you need additional guidance feel free to comment and we can reopen it.
