### ISSUE TITLE
[Question] | How to generate config YAMLs for GridBased tensile tuning?

### ISSUE THREAD

**Issue by rtmadduri** [ROCm/Tensile#2033]
Hello Team, 

We are trying to do Gridbased Tensile tuning for a project and we are following the instructions highlighted over [here](https://github.com/ROCm/tensorflow-private/blob/ff7b41028d24ba4213ebd57f759e699d94d06b74/tensorflow/tools/hipblaslt/README.md) , however, it seems like the config generator only generate YAML files that correspond to [Equality](https://github.com/ROCm/hipBLASLt/tree/develop/library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality) tuning. Are there special instructions to generate [GridBased](https://github.com/ROCm/hipBLASLt/tree/develop/library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/GridBased) tuning YAML files? 

Additionally, I went through a few config files mentioned in your [repo](https://github.com/ROCm/Tensile/blob/develop/Tensile/Configs/rocblas_dgemm_nt_inc1_asm_full.yaml#L58-L83). Can you help me understand what is the difference between Exact and Range? Is that the primary differentiator between Equality and Grid?

cc: @itej89, @feifei14119

**Comment by ppanchad-amd** [comment]
Hi @rtmadduri. Internal ticket has been created to assist with your issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @rtmadduri, Equality and GridBased are different searching methods for kernel selection. Equality is better because the library has the actual GEMM size kernel tuned, and if the library does not have the exact kernel size, it will fall back to GridBased and chose a kernel that is close to the GEMM size. The generated kernel YAML files is found based on this rule. The YAML files found in hipBLASLt are the ones that are tuned and used in the search process of Tensile.

> Additionally, I went through a few config files mentioned in your [repo](https://github.com/ROCm/Tensile/blob/develop/Tensile/Configs/rocblas_dgemm_nt_inc1_asm_full.yaml#L58-L83). Can you help me understand what is the difference between Exact and Range? Is that the primary differentiator between Equality and Grid?

The difference between Exact and Range can be found [here](https://github.com/ROCm/Tensile/wiki/Benchmark-Protocol#problem-sizes). Range specifies a range of sizes to benchmark while Exact specifies the exact size to benchmark.
